version: "3"
services:
    db:
        image: jsurf/rpi-mariadb
        ports:
            - '3306:3306'
        environment:
            - MYSQL_DATABASE=drink_db
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=drinkwater
            - MYSQL_ROOT_PASSWORD=drinkwater

    web:
        build: 
            context: .
            dockerfile: django.dockerfile
        ports:
            - "8000:8000"
        links:
            - db
        depends_on:
            - db