version: "3"
services:
    db:
        restart: always
        image: jsurf/rpi-mariadb
        ports:
            - '3306:3306'
        environment:
            - MYSQL_DATABASE=drink_db
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=drinkwater
            - MYSQL_ROOT_PASSWORD=drinkwater

    web:
        restart: always
        build: 
            context: .
            dockerfile: django.dockerfile
        volumes:
            - .:/home/pi/drink_flow_control
        ports:
            - "8000:8000"
        links:
            - db
        depends_on:
            - db