version: '3'
services: 
    nginx: 
        image: nginx:latest
        container_name: nginx
        ports:
         - 8000:80
        volumes:
          - ./config/nginx/conf.d:/etc/nginx/conf.d
        restart: always
        networks:
            - home
        depends_on:
            - "django"
            - "db"
    django:
        build:
            dockerfile: django.dockerfile
            context: .         
        restart: always
        container_name: django
        ports:
            - 8080:8000
        depends_on:
            - "db"
        networks:
            - "home"

    db:
        image: jsurf/rpi-mariadb
        ports:
            - '3306:3306'      
        environment:
            - MYSQL_DATABASE=drink_db
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=drinkwater
            - MYSQL_ROOT_PASSWORD=drinkwater 
        networks: 
            - home
  
networks:
    home:
        driver: bridge
