version: "3"
services:
  db:
    restart: always
    image: jsurf/rpi-mariadb
    container_name: db
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=drink_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=drinkwater
      - MYSQL_ROOT_PASSWORD=drinkwater 
    networks: 
      - production-network