version: '3'
services: 
    nginx: 
        image: nginx:latest
        container_name: nginx
        ports:
         - 80:80
        volumes:
          - ./config/nginx/conf.d:/etc/nginx/conf.d
        restart: always
        networks:
            - home
        depends_on:
            - "django"
            - "db"
    django:
        build:
            dockerfile: django.dockerfile
            context: .         
        restart: always
        command: python3 manage.py makemigrations && \
                    python3 manage.py migrate && \ 
                    gunicorn drink_flow_control.wsgi:application --bind 0.0.0.0:8000
        container_name: django
        ports:
            - 8000:8000
        depends_on:
            - "db"
        networks:
            - "home"

    db:
        image: tobi312/rpi-mysql
        container_name: db
        ports:
            - '3306:3306'      
        environment:
            - MYSQL_DATABASE=drink_db
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=drinkwater
            - MYSQL_ROOT_PASSWORD=drinkwater 
        networks: 
            - home
  
networks:
    home:
        driver: bridge
