version: "3"
services:
    db:
        image: mysql:5.7
        ports:
        - '3306:3306'
        environment:
        MYSQL_DATABASE: 'drink_db'
        MYSQL_USER: 'admin'
        MYSQL_PASSWORD: 'drinkwater'
        MYSQL_ROOT_PASSWORD: 'drinkwater'
    web:
        django:
            build: .
            command: 
            - python3 manage.py collectstatic --noinput
            - python3 manage.py runserver 0.0.0.0:8000
            ports:
            - "8000:8000"
            links:
            - db
            depends_on:
            - db